id: "web_flask_standard"
name: "Standard Flask Web App"
description: "Python Flaskを使用した堅牢なWebアプリケーション構成"
version: "1.0.0"

triggers:
  keywords: ["web", "flask", "site", "homepage", "アプリ"]
  sample_prompts:
    - "FlaskでToDoアプリを作って"
    - "シンプルなWebサイトを構築したい"

blueprint:
  suggested_tech_stack:
    - "Python 3.10+"
    - "Flask (Web Framework)"
    - "SQLite (Database)"
    - "Bootstrap 5 (CSS Framework)"
  
  core_components:
    - "Application Factory Pattern (create_app)"
    - "Blueprints (ルーティング分割)"
    - "Jinja2 Templates"

  expected_file_structure:
    - "app.py"
    - "requirements.txt"
    - "src/__init__.py"
    - "templates/base.html"

resources:
  domain_knowledge: |
    Flaskアプリでは、グローバル変数を使わず 'Application Factory' パターンを採用してください。
    HTMLは必ず 'templates/base.html' を継承し、重複コードを防ぐこと。
    データベース接続はリクエストごとに確実にクローズすること。